<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">

	<PropertyGroup>
		<Product>DesMeter</Product>
		<AssemblyName>DesMeter</AssemblyName>
		<Version>0.1.10</Version>
		<Authors>deserokk</Authors>
		<Description>In-game combat meter reading IINACT.</Description>
		<Nullable>enable</Nullable>

		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>obj\$(Configuration)\$(AssemblyName).xml</DocumentationFile>
		<NoWarn>$(NoWarn);CS1591</NoWarn>
	</PropertyGroup>

	<Target Name="DropDocXmlBeforePackaging" AfterTargets="Build" BeforeTargets="DefaultDalamudPackagerRelease">
		<Delete Files="$(OutputPath)$(AssemblyName).xml" />
	</Target>

</Project>
